CREATE SCHEMA biller;

CREATE TABLE IF NOT EXISTS `biller`.`blr_ilc_data` (
  `emp_id` VARCHAR(10) NOT NULL,
  `emp_name` VARCHAR(100) NOT NULL,
  `claim_code` VARCHAR(10) NOT NULL,
  `activity` VARCHAR(100) NULL DEFAULT NULL,
  `weekend_date` DATE NULL DEFAULT NULL,
  `total_hours` SMALLINT(3) NULL DEFAULT NULL,
  `shift_type` VARCHAR(10) NULL DEFAULT NULL,
  `us_ind` VARCHAR(10) NULL DEFAULT NULL,
  `on_off_shore` VARCHAR(10) NULL DEFAULT NULL,
  `billing_type` VARCHAR(50) NULL DEFAULT NULL,
  `category` VARCHAR(50) NULL DEFAULT NULL,
  `bam` VARCHAR(100) NULL DEFAULT NULL,
  `app_area` VARCHAR(50) NULL DEFAULT NULL,
  `business_area` VARCHAR(50) NULL DEFAULT NULL,
  `month` VARCHAR(10) NULL DEFAULT NULL,
  `quarter` VARCHAR(2) NULL DEFAULT NULL,
  `dm` VARCHAR(100) NULL DEFAULT NULL,
  `asm` VARCHAR(100) NULL DEFAULT NULL,
  `asd` VARCHAR(100) NULL DEFAULT NULL,
  `wr_no` VARCHAR(20) NULL DEFAULT NULL,
  `is_ticket` VARCHAR(3) NULL DEFAULT NULL,
  `staff_type` VARCHAR(3) NULL DEFAULT NULL,
  `is_ctc` VARCHAR(3) NULL DEFAULT NULL,
  `is_rtc` VARCHAR(3) NULL DEFAULT NULL,
  `planned_hours` SMALLINT(3) NOT NULL,
  `is_billable` VARCHAR(3) NULL DEFAULT NULL,
  `remarks` TEXT NULL DEFAULT NULL,
  `ctc_or_rtc` VARCHAR(10) NULL DEFAULT NULL,
  `work_type` VARCHAR(50) NULL DEFAULT NULL,
  `wr_desc` VARCHAR(150) NULL DEFAULT NULL,
  `cost_center` VARCHAR(25) NULL DEFAULT NULL,
  `category2` VARCHAR(50) NULL DEFAULT NULL,
  `on_off_landed` VARCHAR(25) NULL DEFAULT NULL,
  `tower` VARCHAR(10) NULL DEFAULT NULL,
  `asm_itwr` VARCHAR(100) NULL DEFAULT NULL,
  `asd_itwr` VARCHAR(100) NULL DEFAULT NULL,
  `itwr_actual` SMALLINT(5) NULL DEFAULT NULL,
  `group_type` VARCHAR(25) NULL DEFAULT NULL,
  `vendor_class` VARCHAR(50) NULL DEFAULT NULL,
  `wr_inc_def` VARCHAR(3) NULL DEFAULT NULL,
  `bill_cycle` VARCHAR(10) NULL DEFAULT NULL,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biller`.`blr_sla_data` (
`seq_id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
`weekend_date` DATE NULL DEFAULT NULL,
`asm` VARCHAR(100) NULL DEFAULT NULL,
`asd` VARCHAR(100) NULL DEFAULT NULL,
`asm_itwr` VARCHAR(100) NULL DEFAULT NULL,
`asd_itwr` VARCHAR(100) NULL DEFAULT NULL,
`emp_id` VARCHAR(10) NOT NULL,
`emp_name` VARCHAR(100) NOT NULL,
`activity` VARCHAR(100) NULL DEFAULT NULL,
`work_item` VARCHAR(10) NOT NULL,
`on_off_shore` VARCHAR(10) NULL DEFAULT NULL,
`total_hours` SMALLINT(3) NULL DEFAULT NULL,
`shift_detail` VARCHAR(10) NULL DEFAULT NULL,
`category` VARCHAR(50) NULL DEFAULT NULL,
`bill_type` VARCHAR(50) NULL DEFAULT NULL,
`dm` VARCHAR(100) NULL DEFAULT NULL,
`app_area` VARCHAR(50) NULL DEFAULT NULL,
`business_area` VARCHAR(50) NULL DEFAULT NULL,
`tower` VARCHAR(10) NULL DEFAULT NULL,
`bam` VARCHAR(100) NULL DEFAULT NULL,
`remarks` TEXT NULL DEFAULT NULL,
`is_billable` VARCHAR(3) NULL DEFAULT NULL,
`wr_no` VARCHAR(20) NULL DEFAULT NULL,
`planned_hours` SMALLINT(3) NOT NULL,
`comments` VARCHAR(100) NULL DEFAULT NULL,
`wr_desc` VARCHAR(150) NULL DEFAULT NULL,
`cost_center` VARCHAR(25) NULL DEFAULT NULL,
`fund_type` VARCHAR(20) NULL DEFAULT NULL,
`vendor_class` VARCHAR(50) NULL DEFAULT NULL,
`change_log` VARCHAR(200) NULL DEFAULT NULL,
`active` tinyint(1) NULL default 1,
`modified_by` VARCHAR(50) NULL DEFAULT NULL,
`modified_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`seq_id`))
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biller`.`blr_user` (
  `user_id` VARCHAR(20) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `middle_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `role_id` SMALLINT(2) NOT NULL,
  `email_id` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(45) NOT NULL,
  `delegate_id` VARCHAR(20) NULL,
  `modified_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biller`.`blr_data_lock` (     
   `bill_cycle` VARCHAR(30) NOT NULL,
   `tower` VARCHAR(10) NOT NULL,
   `lock_status` TINYINT(1) NOT NULL DEFAULT '0', 
   `modified_by` VARCHAR(20) NOT NULL,
   `modified_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biller`.`blr_group_approval` (
  `bill_cycle` VARCHAR(30) NOT NULL,
  `dm_approval` TINYINT(2) NULL DEFAULT '0',
  `bam_approval` TINYINT(2) NULL DEFAULT '0',
  `srbam_approval` TINYINT(2) NULL DEFAULT '0',
  `pmo_approval` TINYINT(2) NULL DEFAULT '0',
  `status` TINYINT(1) NOT NULL DEFAULT '0',
  `modified_by` VARCHAR(50) NULL DEFAULT NULL,
  `modified_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biller`.`blr_user_approval` (
  `bill_cycle` VARCHAR(30) NOT NULL,
  `approved_by` VARCHAR(10) NULL DEFAULT NULL,
  `rejected_by` VARCHAR(50) NULL DEFAULT NULL, 
  `modified_by` VARCHAR(50) NULL DEFAULT NULL,
  `modified_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biller`.`blr_role` (
  `role_id` SMALLINT(2) NOT NULL,
  `role_desc` VARCHAR(50) NULL DEFAULT NULL)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biller`.`blr_csdb_data` (
  `emp_id` VARCHAR(10) NOT NULL,
  `emp_name` VARCHAR(100) NOT NULL,
  `email_id` VARCHAR(20) NOT NULL,
  `on_board_date` DATE NULL DEFAULT NULL,
  `role` VARCHAR(30) NULL DEFAULT NULL,
  `cs_number` VARCHAR(10) NULL DEFAULT NULL,
  `bus_area` VARCHAR(50) NULL DEFAULT NULL,
  `expire` DATE NULL DEFAULT NULL,
  `approver_name` VARCHAR(100) NULL DEFAULT NULL,
  `ffic_loc` VARCHAR(25) NULL DEFAULT NULL)
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `biller`.`blr_wiasm_data` (
  `account_id` VARCHAR(10) NOT NULL,
  `work_item` VARCHAR(10) NOT NULL,
  `work_item_desc` VARCHAR(100) NULL DEFAULT NULL,
  `category` VARCHAR(50) NULL DEFAULT NULL,
  `on_off_shore` VARCHAR(10) NULL DEFAULT NULL,
  `bill_type` VARCHAR(50) NULL DEFAULT NULL,
  `application` VARCHAR(20) NULL DEFAULT NULL,
  `bus_area` VARCHAR(50) NULL DEFAULT NULL,
  `dm` VARCHAR(100) NULL DEFAULT NULL,
  `asm` VARCHAR(100) NULL DEFAULT NULL,
  `asd` VARCHAR(100) NULL DEFAULT NULL)
  DEFAULT CHARACTER SET = utf8;

  CREATE TABLE IF NOT EXISTS `biller`.`blr_itwr_data` (
  `req_no` VARCHAR(10) NOT NULL,
  `req_title` VARCHAR(150) NULL DEFAULT NULL,
  `coo_intake_no` VARCHAR(10) NOT NULL,
  `it_sme` VARCHAR(100) NULL DEFAULT NULL,
  `bus_area` VARCHAR(50) NULL DEFAULT NULL,	
  `work_type` VARCHAR(50) NULL DEFAULT NULL,
  `demand_type` VARCHAR(50) NULL DEFAULT NULL,
  `fund_type` VARCHAR(20) NULL DEFAULT NULL,
  `cost_center` VARCHAR(25) NULL DEFAULT NULL,
  `vendor_class` VARCHAR(50) NULL DEFAULT NULL,
  `asm` VARCHAR(100) NULL DEFAULT NULL,
  `primary_vendor` VARCHAR(15) NULL DEFAULT NULL,
  `asd` VARCHAR(100) NULL DEFAULT NULL,
  `overall_status` VARCHAR(30) NULL DEFAULT NULL,
  `vendor_est_hours` VARCHAR(5) NULL DEFAULT NULL,
  `vendor_actual_hours` VARCHAR(5) NULL DEFAULT NULL,
  `pcr_est_hours` VARCHAR(5) NULL DEFAULT NULL,
  `pcr_actual_hours` VARCHAR(5) NULL DEFAULT NULL)
  DEFAULT CHARACTER SET = utf8;
  
  commit;